### ISSUE TITLE
Missing upper case at the beginning of the name of the files and folders.

### ISSUE THREAD

**Issue by LucasAub** [algosup/2023-2024-project-4-sportshield-team-4#17]
### Description

There are some folders and files that didn't start with upper case so you will have to change it in order to respect a certain logic.

### Date

18/03/2024

### Reason for Update

You will have to change it in order to respect a certain logic.

### Proposed Changes

You just have to add an upper case at the beginnig of all folder (ex: management, management_artifact and weekly_reports) and files (all the files in the management folder).

### Importance

4 - Low Priority 😎

### Extra Field

- [x] I want to work on this issue

**Comment by MaximeAlgosup** [comment]
Fixed with commit: e7e06b8e1ad9f5199762cf4314565dbefe50244b
