### ISSUE TITLE
Be more precise on your feature description

### ISSUE THREAD

**Issue by MaximeAlgosup** [algosup/2023-2024-project-4-sportshield-team-4#2]
Document: Functional Specifications
Line(s): 166
Description:
![image](https://github.com/algosup/2023-2024-project-4-sportshield-team-4/assets/145995231/dbf09e16-d434-4f1c-95d4-f1e3f4f93c1f)
You need to be more precise in the definition of the features, for example if you talk about the battery lifespan you should say something like: currently the battery lifespan is 3 days but, it should be at least 7.

**Comment by LucasAub** [comment]
OK, I changed it in the commit: e8c085f858b9812364f23b11a64299b5018089a9
