### ISSUE TITLE
TECHNICAL SPECIFICATION ISSUE

### ISSUE THREAD

**Issue by habicll** [algosup/2023-2024-project-4-sportshield-team-4#22]
### Description

The description is not enough detailed in the hardware part with the pictures.

### Date

19/03/2024

### Reason for Update

So the document is more understandable... 

### Proposed Changes

developed more the component in the hardware part...

### Importance

4 - Low Priority 😎

### Extra Field

- [x] I want to work on this issue

**Comment by AlexisLasselin** [comment]
It has been done so you may check and close the issue

**Comment by habicll** [comment]
look good to me.
