### ISSUE TITLE
TECHNICAL SPECIFICATION ISSUE

### ISSUE THREAD

**Issue by habicll** [algosup/2023-2024-project-4-sportshield-team-4#23]
### Description

- The Electronic Configuration should be more detailed because there is only a picture but we don't understand what is it....
- Inside the "MILESTONE" part at the first milestone you wrote "The device's battery life is extended to 7 days under optimal conditions" 
- The III.2.E need more details
- III.6 The reduction strategies should be specific and actionable, detailing the steps to be taken to mitigate the identified liabilitie.

### Date

19/03/2024

### Reason for Update

clarity.

### Proposed Changes

- Explain what is it.
- You should maybe write "  The device's battery life is extended to 7 days under normal usage conditions".
- Add more details such as response time and ease of use.
- Consider providing more details on the testing and validation processes to be conducted.

### Importance

3 - Normal Priority 🆗

### Extra Field

- [x] I want to work on this issue

**Comment by AlexisLasselin** [comment]
Except the electronic map, because I cannot explain it, I don't understand anything, the changes has been done here:

38b4af90a706ff40e2eddf910cef326cd3983e6a

**Comment by habicll** [comment]
same look good to me.
