### ISSUE TITLE
ISSUE PROJECT CHARTER

### ISSUE THREAD

**Issue by habicll** [algosup/2023-2024-project-4-sportshield-team-4#24]
### Description

- In responsibilities : there is no explanation of what "R" "A" "C" and "I" are...

- The definitions in the glossary are a bit too vague.

### Date

19/03/2024

### Reason for Update

understanding.

### Proposed Changes

- In responsibilities : add a explanation of what "R" "A" "C" and "I" are because we don't understand when we watch it the first time, and if we click on the link we loose our page and we have to go back to the first page and restart your doc from the beginning so its a bit long....

- Define more your term in the glossary (like for NFC you said “ Near Field Communication “  but its not very concrete and i still don't really understand what it is...) or you can add a link for a site that define the specific term .

This for example : "https://developer.android.com/develop/connectivity/nfc#:~:text=Near%20Field%20Communication%20(NFC)%20is,between%20two%20Android-powered%20devices. " .
 
The rest is good work well done 👍.

### Importance

3 - Normal Priority 🆗

### Extra Field

- [ ] I want to work on this issue

**Comment by MaximeAlgosup** [comment]
Corrected with commit d0ad581bded5b23087d967ed06440ae3abb7ceb5
