### ISSUE TITLE
ISSUE NFC Component Troubleshooting Guide

### ISSUE THREAD

**Issue by habicll** [algosup/2023-2024-project-4-SPORTSHIELD-team-4#32]
### Description

- In the "Library Absence" you wrote "The primary reason for the NFC component's failure to function with the Arduino Xiao BLE board is the absence of a suitable library. " I think that the sentence lack of sense and should be review...

### Date

27/03/2024

### Reason for Update

To ensure clarity like hyalin.

### Proposed Changes

instead of ""The primary reason for the NFC component's failure to function with the Arduino Xiao BLE board is the absence of a suitable library." you should write "The primary reason for the NFC component's failure to work with the Arduino Xiao BLE board is the absence of a suitable library."

### Importance

4 - Low Priority 😎

### Extra Field

- [ ] I want to work on this issue

**Comment by LucasAub** [comment]
Fixed in this commit c3a3a1152ae2f71481ef23c400d754fb702aa24e
