### ISSUE TITLE
Typos in the Project Charter

### ISSUE THREAD

**Issue by AlexisLasselin** [algosup/2023-2024-project-4-sportshield-team-4#9]
There is a small typo in the project_charter.md, the line 76 is the following:

`For this project reposbilities are as follows:`

but it should be:

`For this project responsibilities are as follows:`

There is also line 107:

`And we will present the projet to the client on the 2024/04/19.`

where projet should be project and you also don't put "the" before a date:

`And we will present the project to the client on 2024/04/19.`

Line 120:

`The team will have access to the entire already developped software and the documentation.`

Developed is only one p so the correct line is:

`The team will have access to the entire already developed software and the documentation.`

Line 135:

`| Tests results can be bad interpreted. | Medium | The team will define clear testing procedures and will use KPI's to monitor the progress of the project. |`

You need to replace bad by badly:

`| Tests results can be badly interpreted. | Medium | The team will define clear testing procedures and will use KPI's to monitor the progress of the project. |`

Once you're done with the previous changes, you can add me to the approvals.

**Comment by MaximeAlgosup** [comment]
Corrected with commit ae1779a9667c7aaa354dfa7b39fc5e512c1e26d4
